##########################################
# Docker Compose configuration
##########################################

# Run 'dockerBuildAll.sh' first to create application images.

# Traefik dashboard: http://localhost:8080/
# Main: http://localhost
# App1 FrontEnd: http://app1.localhost/
# App1 API status: http://app1.localhost/api/status


services:

  ##########################################
  # Service: Traefik - Reverse proxy and load balancer
  ##########################################
  traefik:
    image: traefik:v3.7
    restart: always
    command:
      - "--log.level=ERROR"
      - "--accesslog=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--api.insecure=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  ##########################################
  # Service: Main FrontEnd
  ##########################################
  main-frontend:
    image: main-frontend:latest
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.main-frontend.rule=Host(`localhost`)"

  ##########################################
  # Service: App1 FrontEnd
  ##########################################
  app1-frontend:
    image: app1-frontend:latest
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app1-frontend.rule=Host(`app1.localhost`)"

  ##########################################
  # Service: App1 BackEnd
  ##########################################
  app1-backend:
    image: app1-backend:latest
    restart: always
    ports:
      - ":80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app1-backend.rule=Host(`app1.localhost`) && PathPrefix(`/api`)"

