##########################################
# KPTN VPS Docker Compose configuration
##########################################

services:

  ##########################################
  # Service: KPTN Main FrontEnd
  ##########################################
  kptn-main-frontend:
    image: kptn-main-frontend:latest
    ports:
      - 8080:80
    restart: always

  ##########################################
  # Service: KPTN App1 FrontEnd
  ##########################################
  kptn-app1-frontend:
    image: kptn-app1-frontend:latest
    ports:
      - 8081:80
    restart: always

  ##########################################
  # Service: KPTN App1 BackEnd
  ##########################################
  kptn-app1-backend:
    image: kptn-app1-backend:latest
    ports:
      - 8091:80
    restart: always

  ##########################################
  # Service: KPTN App1 Database
  ##########################################
  # todo

###################################################
# Volumes
#
# Persistant data for the database service.
# We are only using default values, hence the lack of any configuration for the volume.
###################################################
#volumes:
#  database-data:
